Sprint_2
miroshnichenkoolga/qa_python pull request #2
Opened 2023-07-23 12:58 UTC by miroshnichenkoolga

2023-07-23 14:18 UTC, kadirovgm requested changes
Поправь комменты, а также добавь в одном из тестов параметризацию

2023-07-23 14:18 UTC, kadirovgm commented on README.md
> +### Списok реализованных тестов
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-07-23 14:18 UTC, kadirovgm commented on main.py
спасибо, что поправила задание!

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert len(gotBooks) == wantCount
нужно исправить: мы должны придерживаться принципа атомарности тестов: один тест-одна проверка (один ассерт), здесь нужно либо объединить в один ассерт либо поделить тест на разные тесты

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        count = len(collector.get_books_genre())
нужно исправить: не нужно перед тестом проверять количество книг, так как для объекта collector, созданного внутри метода количество книг каждый раз будет 0, так как это каждый раз новый объект

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        got = gotBooks.get(wantBook)
нужно исправить: не пользуемся такими методами, только существующими из задания (get_books_genre, get_book_genre)

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_one_book_true(self):
можно лучше: здесь достаточно проверить: что после добавления книги количество книг в словаре books_genre равно один

другой проверкой является проверка того, что именна добавленная книга находится в словаре

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert got is not None
нужно исправить: лишняя проверка, если она равна какому то числу, то априори она будет not None

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +                              '50Симплициссимус: Ганс Якоб Кристо Гриммельсгаузен'])
можно лучше: 42 и 50 находятся в одном эквивалентом классе, так что проверка этих двух значений является излишним

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        got = gotBooks.get(name_book)
нужно исправить: пользуемся только get_books_genre, можно было проверить что get_books_genre = {}

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert got == want
правильно

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +    def test_get_book_genre_positive_result(self):
можно лучше: кажется эта проверка полностью повторяет проверку выше test_set_book_genre_one_book_true, либо надо удалить, либо в одном проверить что именно нужная книга есть в словаре через in/not in

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_for_children() != [name]
можно лучше: is None

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == [name]
нужно исправить: скорее тут нужно проверить, что книги в списке favorites не дублируются, то есть посчитать количество = 1, иначе если даже задублируются, твой тест пройдет, ведь книга будет в спике

2023-07-23 14:18 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == []
верно)

2023-07-24 09:27 UTC, miroshnichenkoolga commented on tests.py
> +        assert collector.get_list_of_favorites_books() == [name]
этот тест верный

вот пример, что если книга задублируется, тест не пройдет`tests.py:98 (TestBooksCollector.test_add_book_in_favorites_add_same_book_twice_negative_result)
['Зди15', 'Зди15'] != ['Зди15']

Expected :['Зди15']
Actual   :['Зди15', 'Зди15']

2023-07-25 07:04 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books() == [name]
такс, да, тут я ошибся, почему то подумал что проверка с in/not in

2023-07-25 07:06 UTC, kadirovgm approved these changes

2023-07-25 07:43 UTC, merged